### ISSUE TITLE
Package doesn't follow ESLint naming convention

### ISSUE THREAD

**Issue by matthieubosquet** [solid/eslint-config-base#1]
ESLint [shareable configuration packages](https://eslint.org/docs/developer-guide/shareable-configs#creating-a-shareable-config) names require a **'eslint-config-'** prefix.

Therefore this repository was renamed from 'eslint-base-config' to 'eslint-config-base'.

See also: https://github.com/solid/eslint-config-base/commit/9a20aa939b9e060eb357e3ecda379d72f34c60d2#commitcomment-45287438

We need to delete the first published package that ESLint fails to see and manually publish a first version of 'eslint-config-base'.

**Comment by RubenVerborgh** [comment]
Done: https://www.npmjs.com/package/@solid/eslint-config-base
